version: 0.0
os: centos
files:
  - source: /
    destination: /home/centos

hooks:
  AfterInstall:
    - location: ./infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: centos
  ApplicationStart:
    - location: ./infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: centos
