version: 0.0
os: linux
files:
  - source: /
    destination: /home/centos

hooks:
  ApplicationStart:
    - location: ./infrastructure/aws/codedeploy/afterInstall.sh
      timeout: 180
      runas: centos
