version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - run:
          name: Install packages
          command:
            sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y

      - run:
          name: Install node & npm
          command: |
            sudo apt install curl -y
            curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
            sudo apt install nodejs -y
            sudo apt install npm -y

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'

      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set default.region us-east-1
      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            ls -al
            npm install
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cd codedeploy_artifact
            cp ../* .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip .
            rm *.yml *.sh *.properties *.jar *.json
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp csye6225-web-app-${CIRCLE_BUILD_NUM}.zip --recursive codedeploy_artifact s3://${CODE_DEPLOY_S3_BUCKET}
      - run:
          name: Make CodeDeploy API call
          command: |
            aws deploy create-deployment --output json --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name csye6225-webapp-deployment --s3-location bucket=${CODE_DEPLOY_S3_BUCKET},bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
